#server:
#  port: 8082
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/microservice
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    open-in-view: false  # Disable if not needed
